server:
  port: 80
  undertow:
    io-threads: 1
    worker-threads: 8
    buffer-size: 512
    direct-buffer: true

spring:
  application:
    name: cloud-order-service
  devtools:
    restart:
      enabled: false
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1
eureka:
  client:
    #表示向注册中心注册自己
    register-with-eureka: true
    #表示是否eurekaserver抓取已有的注册信息，在集群下有必要
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka #,http://eureka7002.com:7002/eureka

logging:
  level:
    web: debug
