server:
  port: 9003
  undertow: #undertow配置
    io-threads: 1
    worker-threads: 8
    buffer-size: 512
    direct-buffer: true

spring:
  application:
    name: nacos-consumer-order
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

service-url:
  nacos-user-service: http://nacos-provider-payment

management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    web: debug
