server:
  port: 8001
  undertow: #undertow配置
    io-threads: 1
    worker-threads: 8
    buffer-size: 512
    direct-buffer: true

spring:
  application:
    name: cloud-payment-service
  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource  #当前数据源操作类型
    type: com.zaxxer.hikari.HikariDataSource #使用hikari
    driver-class-name: com.mysql.cj.jdbc.Driver #数据库驱动包
    url: jdbc:mysql://localhost:3306/cloud?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: 123456
    hikari: #hikari连接池配置
      connection-timeout: 20000
      minimum-idle: 5
      maximum-pool-size: 10
      max-lifetime: 200000
      auto-commit: true
  devtools:
    restart:
      enabled: false #是否热部署重启
  zipkin:
    base-url: http://localhost:9411 #zipkin的服务器地址
  sleuth:
    sampler:
      probability: 1 #采样率0~1之间，一般0.5


eureka:
  client:
    #表示向注册中心注册自己
    register-with-eureka: true
    #表示是否eurekaserver抓取已有的注册信息，在集群下有必要
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka #,http://eureka7002.com:7002/eureka
  instance:
    prefer-ip-address: true #显示ip，端口号
    instance-id: payment8001 #自定义主机实例名（无所谓自定义）
    #lease-expiration-duration-in-seconds: 4 #(租约到期期限) 等待心跳超时时间，默认为90秒
    #lease-renewal-interval-in-seconds: 2 #（租约更新间隔）心跳发送间隔时间，默认30秒

logging:
  level:
    web: debug

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.atguigu.springcloud.entities

#actuator/info的信息
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      #获得/actuator/info 如果为null，可以使用maven->plugins->spring-boot-spring-boot-info 运行