server:
  port: 7001
  undertow:
    io-threads: 1
    worker-threads: 8
    buffer-size: 512
    direct-buffer: true
eureka:
  instance:
    hostname: eureka7001.com
  client:
    #表示不向注册中心注册自己
    register-with-eureka: false
    #表示我是注册中心
    fetch-registry: false
    service-url:
      #与eureka server交互的地址查询服务与注册服务都依赖这地址
      #defaultZone: http://eureka7002.com:7002/eureka/
      #单机模式，写自己的url
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  #server:
   # peer-node-read-timeout-ms: 1000
  #enable-self-preservation: false #是否开启eureka自我保护机制，默认开启
    #eviction-interval-timer-in-ms: 2000 #清理无效注册信息时间，默认为60000毫秒
spring:
  devtools:
    restart:
      enabled: false

logging:
  level:
    web: info