server:
  port: 8005

spring:
  application:
    name: cloud-consul-paymeny
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        hostname: 127.0.0.1
        service-name: ${spring.application.name}
        port: ${server.port}